name: CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHON_VENV: .venv

    steps:
      - name: Debug compiler versions
        run: |
          python3 --version
          g++ --version
          make --version
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.14

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/main/solver/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m venv $PYTHON_VENV
          $PYTHON_VENV/bin/python -m pip install --upgrade pip
          $PYTHON_VENV/bin/pip install -r src/main/solver/requirements.txt

      - name: Run Maven verify
        run: mvn clean verify